application_config:
  display_license: false
  display_copyright: false
  license: 
    - 'http://purl.org/dc/terms/license'
  copyright:
    - 'http://www.omg.org/techprocess/ab/SpecificationMetadata/copyright'
    - 'https://www.omg.org/spec/Commons/AnnotationVocabulary/copyright'  