services:
  fibo-strapi:
    image: edmcouncil/fibo-strapi:${HTML_BRANCH:-develop}
    build:
      context: https://github.com/edmcouncil/html-pages.git#${HTML_BRANCH:-develop}:general/strapi
      args:
        - ONTPUB_FAMILY=fibo
        - BRANCH_NAME=${HTML_BRANCH:-develop}
    volumes:
      - spec_root:/opt/html-pages
  fibo-pages:
    image: edmcouncil/fibo-pages:${HTML_BRANCH:-develop}
    build:
      context: https://github.com/edmcouncil/html-pages.git#${HTML_BRANCH:-develop}:general
      args:
        - ONTPUB_FAMILY=fibo
        - BRANCH_NAME=${HTML_BRANCH:-develop}
    environment:
      - STRAPI_URL=http://fibo-strapi:1337
    volumes:
      - spec_root:/opt/html-pages
    depends_on:
      - fibo-strapi
  fibo-viewer:
    image: edmcouncil/onto-viewer:${VIEWER_BRANCH:-develop}
    build:
      context: .
    environment:
      - ONTPUB_FAMILY=fibo
      - UPDATE_URL=${FIBO_UPDATE_URL:-https://spec.edmcouncil.org/fibo/ontology/etc/onto-viewer-web-app/config/}
  spec:
    image: edmcouncil/spec:${HTML_BRANCH:-develop}
    build:
      context: https://github.com/edmcouncil/html-pages.git#${HTML_BRANCH:-develop}:home
      args:
        - BRANCH_NAME=${HTML_BRANCH:-develop}
    environment:
      - FAMILY_REGEX=fibo
    volumes:
      - spec_root:/opt/html-pages
    depends_on:
      - fibo-strapi
      - fibo-pages
      - fibo-viewer
    ports:
      - 8080:80

volumes:
  spec_root:
