# For this docker-compose.yaml file to work, the following folder outline is required:
#
#   aRootDir/
#     onto-viewer/            (https://github.com/edmcouncil/onto-viewer)
#       docker-compose.yaml   <- this file
#         ...
#     html-pages/             (https://github.com/edmcouncil/html-pages)
#       ...

version: "3.8"

services:
  onto-viewer-server:
    container_name: onto-viewer-server
    build:
      context: .
      dockerfile: ./docker/server/Dockerfile
    ports:
      - "6101:8080"
    volumes:
      - ./docker/init-onto-viewer.sh:/opt/develop/init-onto-viewer.sh
      - .:/opt/develop/src
      - ./docker/runtime/.m2:/opt/develop/.m2
      - ./docker/runtime/server:/opt/develop/app_home
    networks:
      - default

  onto-viewer-web:
    container_name: onto-viewer-web
    build:
      context: ../onto-viewer-web
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - onto-viewer-server
      - strapi
    networks:
      - default

  strapi:
    container_name: onto-viewer-strapi
    build:
      context: ../strapi-dashboard
      dockerfile: Dockerfile
    ports:
      - "1337:1337"
    networks:
      - default