version: "3.8"

services:
  onto-viewer-server:
    container_name: onto-viewer-server
    environment: 
      - ONTPUB_FAMILY=${ONTPUB_FAMILY:-dev}
      - UPDATE_URL
    build:
      context: .
      dockerfile: ./docker/server/Dockerfile
    ports:
      - "6101:8080"

    volumes:
      - ./docker/init-onto-viewer.sh:/opt/develop/init-onto-viewer.sh
      - .:/opt/develop/src
      - ./docker/runtime/.m2:/opt/develop/.m2
      - ./docker/runtime/server:/opt/develop/app_home
    networks:
      - default
  web-with-strapi: 
    container_name: onto-viewer-web-with-strapi
    environment: 
      - PUBLIC_URL=0.0.0.0
      - NUXT_PORT=3000
      - ONTPUB_FAMILY=${ONTPUB_FAMILY:-dev}
    build:
      context: ./docker/web
    ports: 
      - 3000:3000
      - 1337:1337
    networks:
      - default