services:
  dev-strapi:
    image: edmcouncil/dev-strapi:${HTML_BRANCH:-latest}
    build:
      context: https://github.com/edmcouncil/html-pages.git#${HTML_BRANCH:-develop}:general/strapi
      args:
        - ONTPUB_FAMILY=dev
        - BRANCH_NAME=${HTML_BRANCH:-develop}
    volumes:
      - spec_root:/opt/html-pages
  dev-pages:
    image: edmcouncil/dev-pages:${HTML_BRANCH:-latest}
    build:
      context: https://github.com/edmcouncil/html-pages.git#${HTML_BRANCH:-develop}:general
      args:
        - ONTPUB_FAMILY=dev
        - BRANCH_NAME=${HTML_BRANCH:-develop}
    environment:
      - STRAPI_URL=http://dev-strapi:1337
    volumes:
      - spec_root:/opt/html-pages
    depends_on:
      - dev-strapi
  dev-viewer:
    image: edmcouncil/onto-viewer:${TAG:-latest}
    build:
      context: .
      dockerfile: ./Dockerfile.onto-viewer
    environment:
      - ONTPUB_FAMILY=dev
    # uncomment to use custom ontology and config files located in, respectively, "./onto-viewer-web-app/ontologies" and "./onto-viewer-web-app/config" folders
    #volumes:
      # - ./onto-viewer-web-app/ontologies:/opt/viewer/ontologies
      # - ./onto-viewer-web-app/config:/opt/viewer/config
  spec:
    image: edmcouncil/spec:${HTML_BRANCH:-latest}
    build:
      context: https://github.com/edmcouncil/html-pages.git#${HTML_BRANCH:-develop}:home
      args:
        - BRANCH_NAME=${HTML_BRANCH:-develop}
    environment:
      - FAMILY_REGEX=dev
    volumes:
      - spec_root:/opt/html-pages
    depends_on:
      - dev-strapi
      - dev-pages
      - dev-viewer
    ports:
      - 8080:80

volumes:
  spec_root:
