services:
  fibo-strapi:
    image: edmcouncil/fibo-strapi:latest
    volumes:
      - opt:/opt
  fibo-pages:
    image: edmcouncil/fibo-pages:latest
    environment:
      - STRAPI_URL=http://fibo-strapi:1337
    volumes:
      - opt:/opt
    depends_on:
      - fibo-strapi
  fibo-viewer:
    image: edmcouncil/onto-viewer:latest
    build:
      context: .
      dockerfile: ./Dockerfile.onto-viewer
    environment:
      - ONTPUB_FAMILY=fibo
      - UPDATE_URL=${FIBO_UPDATE_URL:-https://spec.edmcouncil.org/fibo/ontology/etc/onto-viewer-web-app/config/}
  spec:
    image: edmcouncil/spec:latest
    environment:
      - FAMILY_REGEX=fibo
    volumes:
      - opt:/opt
    depends_on:
      - fibo-strapi
      - fibo-pages
      - fibo-viewer
    ports:
      - 8080:80

volumes:
  opt:
