groups_config:
  priority_list:
    - http://www.w3.org/2000/01/rdf-schema#subClassOf
    - http://www.w3.org/2000/01/rdf-schema#seeAlso
  groups:
    - name: Glossary
      items:
        - http://www.w3.org/2000/01/rdf-schema#label
    - name: This ontology contains
      items:
        - '@viewer.internal.clazz'
        - '@viewer.external.clazz'
        - '@viewer.internal.objectProperty'
        - '@viewer.external.objectProperty'
        - '@viewer.internal.dataProperty'
        - '@viewer.external.dataProperty'
        - '@viewer.internal.instance'
        - '@viewer.external.instance'
        - '@viewer.internal.annotationProperty'
        - '@viewer.external.annotationProperty'
        - '@viewer.internal.dataType'
        - '@viewer.external.dataType'
    - name: Ontological characteristic
      items:
        - '@viewer.function.usage_classes'
        - '@viewer.function.direct_sub_data_property'
        - '@viewer.function.direct_sub_object_property'
        - '@viewer.function.direct_sub_annotation_property'
        - '@viewer.function.direct_subclasses'
        - '@viewer.function.instances'
        - '@viewer.axiom.EquivalentClasses'
        - '@viewer.axiom.SubClassOf'
        - '@viewer.function.anonymous_ancestor'
        - '@viewer.axiom.DisjointClasses'
        - '@viewer.axiom.ClassAssertion'
        - '@viewer.axiom.SameIndividual'
        - '@viewer.axiom.ObjectPropertyAssertion'
        - '@viewer.axiom.DataPropertyAssertion'
        - '@viewer.axiom.SubObjectPropertyOf'
        - '@viewer.axiom.SubDataPropertyOf'
        - '@viewer.axiom.SubAnnotationPropertyOf'
        - '@viewer.axiom.EquivalentObjectProperties'
        - '@viewer.axiom.EquivalentDataProperties'
        - '@viewer.axiom.ObjectPropertyDomain'
        - '@viewer.axiom.DataPropertyDomain'
        - '@viewer.axiom.ObjectPropertyRange'
        - '@viewer.axiom.FunctionalObjectProperty'
        - '@viewer.axiom.DataPropertyRange'
        - '@viewer.axiom.AnnotationPropertyDomain'
        - '@viewer.axiom.AnnotationPropertyRangeOf'
        - '@viewer.axiom.InverseObjectProperties'
    - name: Meta-information
      items:
        - 'http://www.w3.org/2004/02/skos/core#changeNote'
        - 'http://www.w3.org/2004/02/skos/core#note'
        - 'http://www.w3.org/2000/01/rdf-schema#comment'
        - 'http://www.w3.org/2000/01/rdf-schema#isDefinedBy'
        - 'http://www.w3.org/2000/01/rdf-schema#seeAlso'
        - 'http://www.w3.org/2004/02/skos/core#historyNote'

search_config:
  search_descriptions:
    - http://www.w3.org/2004/02/skos/core#definition
    - http://purl.org/dc/terms/abstract
  fuzzy_distance: 3
  reindex_on_start: true
  find_properties:
    - label: RDFS Label
      identifier: rdfs_label
      iri: http://www.w3.org/2000/01/rdf-schema#label
    - label: SKOS Definition
      identifier: skos_definition
      iri: http://www.w3.org/2004/02/skos/core#definition
    - label: SKOS Note
      identifier: skos_note
      iri: http://www.w3.org/2004/02/skos/core#note
    - label: PURL Description
      identifier: purl_description
      iri: http://purl.org/dc/terms/description
    - label: SKOS Example
      identifier: skos_example
      iri: http://www.w3.org/2004/02/skos/core#example
    - label: SKOS Scope Note
      identifier: skos_scopeNote
      iri: http://www.w3.org/2004/02/skos/core#scopeNote

ontologies:
  - url: http://example.com
  - path: foo/bar/my_dir
  - path: foo/my_ontology.rdf
