package org.edmcouncil.spec.ontoviewer.core.model;

/**
 * @author Michał Daniel (michal.daniel@makolab.com)
 * @author Patrycja Miazek (patrycja.miazek@makolab.com)
 */
public enum OwlType {

  ANNOTATION_PROPERTY,
  STRING,
  IRI,
  ANY_URI,
  AXIOM,
  CLASS, TAXONOMY, OTHER, AXIOM_CLASS,
  AXIOM_DATA_PROPERTY,
  AXIOM_OBJECT_PROPERTY,
  AXIOM_ANNOTATION_PROPERTY,
  AXIOM_NAMED_INDIVIDUAL,
  AXIOM_DATATYPE,
  DIRECT_SUBCLASSES,
  INSTANCES,
  ANONYMOUS_ANCESTOR,
  MODULES,
  RESOURCES_IRI,
  USAGE_CLASSES,
  DIRECT_SUB_OBJECT_PROPERTY,
  DIRECT_SUB_ANNOTATION_PROPERTY,
  INDIVIDUAL,
  DIRECT_SUB_DATA_PROPERTY,
  OBJECT_PROPERTY,
  DATATYPE,
  DATA_PROPERTY

}
